inherit_from: .rubocop_todo.yml
inherit_gem:
  theforeman-rubocop:
    - lenient.yml

AllCops:
  TargetRubyVersion: 2.7

# Cop supports --auto-correct.
# Configuration parameters: AllowForAlignment, ForceEqualSignAlignment.
Layout/ExtraSpacing:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: with_first_parameter, with_fixed_indentation
Layout/ParameterAlignment:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, IndentationWidth.
# SupportedStyles: aligned, indented
Layout/MultilineOperationIndentation:
  Enabled: true

# Cop supports --auto-correct.
Layout/EmptyLines:
  Enabled: true

Metrics/ModuleLength:
  Exclude:
  - test/**/*

Style/LambdaCall:
  Enabled: false
