inherit_from: .rubocop_todo.yml

# Cop supports --auto-correct.
# Configuration parameters: AllowForAlignment, ForceEqualSignAlignment.
Style/ExtraSpacing:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: IndentationWidth.
Style/IndentAssignment:
  Enabled: true