sudo: false
language:
  - ruby

before_install: >-
  if ruby -v | grep 'ruby 2.2'; then
    gem install bundler -v '~> 1.17'
  fi

rvm:
  - "2.2.2"
  - "2.3.1"
  - "2.4.0"
  - "2.5.0"

env:
  global:
    - "TESTOPTS=--verbose DB=postgresql DB_CONN_STRING=postgres://postgres@localhost/travis_ci_test"

matrix:
  include:
    - rvm: "2.4.0"
      env: "DB=mysql DB_CONN_STRING=mysql2://root@localhost/travis_ci_test"
    - rvm: "2.4.0"
      env: "DB=sqlite3 DB_CONN_STRING=sqlite:/"
    - rvm: "2.4.0"
      env: "CONCURRENT_RUBY_EXT=true"

install:
  - test/prepare_travis_env.sh

script:
  - bundle exec rubocop
  - bundle exec rake test
